modLoader = "javafml"
loaderVersion = "[43,)"
license="${mod_license}"

[[mods]]
modId = "create_gravity"
displayTest="IGNORE_ALL_VERSION"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/create-gravity"
authors = "${mod_author}"
description = '''
${mod_description}
'''
itemIcon = "minecraft:end_stone"

[[dependencies.create_gravity]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_gravity]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"